id: A42624E2A
title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
type: translation
pechas:
- IA3BFA004
- I5045C01F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:42:47.573875
  last_modified_at: 2023-01-04 12:42:47.573890
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IA3BFA004/88E3: '9992'
  I5045C01F/4474: '9992'
